### ISSUE TITLE
server: Issuer verification fails

### ISSUE THREAD

**Issue by YouQam** [mint-o-badges/badgr-server#10]
When [verifying an issuer](https://api.openbadges.education/staff/issuer/issuer/5/change/) at the deployed admin interface, it fails with an error ("We're sorry, an error has occurred.").

**Comment by YouQam** [comment]
I managed to resolve the issue by updating the docker-compose file in the server, so no pull request was needed to apply changes.

**Comment by jona159** [comment]
Going to close, since this is in ```Done```
