### ISSUE TITLE
server: update account confirmation email

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-server#102]
New design can be found here: https://www.figma.com/file/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?type=design&node-id=2887-6645&mode=design&t=8QD6fG8uLVLR16Kb-4

In case you need some input / graphics please get in touch with @Annicelia

**Comment by umut0** [comment]
We currently have the following footer for Emails: 

![Image](https://github.com/mint-o-badges/badgr-server/assets/2675557/263a1e83-b4e8-444c-ae32-e3499a6ab8a8)

Do we really want to delete that one and replace it with just the link?

Also i think it is good practice to provide the link for copying. Currently it looks like this:

![Image](https://github.com/mint-o-badges/badgr-server/assets/2675557/7b73f920-3029-43ca-bc7b-69768ae0e5b9)

**Comment by Annicelia** [comment]
Hey @umut0, thank you, you are welcome to leave the link as it is.
Copy: Could you please adopt the comma after "Account" and change the capital D to "d" (...**d**einen Account**,** um Badges...) 
Button: Could you please round the corners 
Footer: can you make it look like this? :)
![Bildschirmfoto 2024-05-21 um 12 06 57](https://github.com/mint-o-badges/badgr-server/assets/164371483/9381d2db-8d52-43ee-b8d7-ef3a54a00cdd)

**Comment by jona159** [comment]
Done in #111
