### ISSUE TITLE
server: creating a new badge using deployed version fails

### ISSUE THREAD

**Issue by YouQam** [mint-o-badges/badgr-server#11]
Unlike running the app locally, creating a new badge using deployed version fails with the error:
> Unable to create Badge Class: <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx/1.25.2</center> </body> </html>

**Comment by timber-they** [comment]
@YouQam are you working on this?

**Comment by timber-they** [comment]
Um es zusammenzufassen:

- Ich hatte den Server auf nginx umgestellt, dann kam wieder genau der gleiche Fehler
- Ich hab das Skript von Felix laufen lassen, das hat die URLs gefixt und den Fehler gelöst
- Dazu hab ich eine PR erstellt und schon deployed (aber noch nicht gemerged)
- Ich hab wieder zurück auf traefik gewechselt, die nginx Config aber auf dem Server liegen lassen
- Aus irgendeinem Grund läuft das Admin Interface (api.openbadges.education/staff) nicht mehr; dafür hab ich allerdings keine Zeit mehr

**Comment by jona159** [comment]
The linked PR was merged and the ticket is in ```Done```, going to close
