### ISSUE TITLE
server: re-creating a user with same name and/or email does not work

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-server#115]
When an account is deleted via the staff backend and I want to recreate an account with the same name and email address, I receive a rather cryptic (although, from an artistic point of view, interesting) error message:  

![Image](https://github.com/mint-o-badges/badgr-server/assets/2930332/9916e1aa-37a8-438e-a6aa-81a70895e748)

[account_creation_error.txt](https://github.com/user-attachments/files/15955853/account_creation_error.txt)

The error message above can be rendered as html in a browser. Exception is `BadgeUser matching query does not exist.` and seems to be related to a cached email address.

**Comment by timber-they** [comment]
I can't reproduce this (anymore).

If I'm not mistaken we did change our cache backend in the meantime from `python-memcached` to `pymemcache`. I then wasn't aware that it also needed to be changed in the settings and added the other dependency again. So with this ticket I'm going to remove the dependency (again), which seems to solve the issue.

If the project doesn't compile for you anymore, remember to change the settings accordingly (similar to the example settings' `CACHE` section.

**Comment by zven** [comment]
I also couldn't reproduce the error anymore. So it seems to be indeed fixed. 👍
