### ISSUE TITLE
server: email-confirmation of new account is not possible after few hours

### ISSUE THREAD

**Issue by YouQam** [mint-o-badges/badgr-server#154]
While the error msg says:

![Image](https://github.com/mint-o-badges/badgr-server/assets/40634685/3cef04b9-a4d1-4aaa-9aae-cd1abf50d6ff)

an error occurred when trying to create a new account 

![Image](https://github.com/mint-o-badges/badgr-server/assets/40634685/ce27aa2e-2783-469b-9fb5-3f19cb90e6cf)

**Comment by zven** [comment]
for reviewer: Wait for 2-3 hours and see if it works (according to @YouQam )

**Comment by YouQam** [comment]
**Update:** for reviewers just wait 5 minutes after creating a new account then click on `Meinen Account bestätigen` on received email. You should see:
![Image](https://github.com/mint-o-badges/badgr-server/assets/40634685/3cef04b9-a4d1-4aaa-9aae-cd1abf50d6ff)

**Comment by YouQam** [comment]
It seems the issue occurred only locally. I couldn't reproduce it in staging.
