### ISSUE TITLE
server: update imageFrame info when editing a badge

### ISSUE THREAD

**Issue by jona159** [mint-o-badges/badgr-server#165]

**Comment by YouQam** [comment]
@jona159 Can you elaborate what issue updating image-frame will resolve? or why do we need it?

**Comment by jona159** [comment]
@YouQam Sure, currently when a badge is edited and the editor changes the badge image from having a frame to a custom image (not having a frame), this information is not saved in the DB. So the information would be that the badge still has a frame when it does not. This PR should solve this
