### ISSUE TITLE
creation of institution fails

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-server#17]
Atm, the creation of a new institution on openbadges.education fails and only a cryptic / unformatted error message is displayed.

![Image](https://github.com/mint-o-badges/badgr-server/assets/2930332/a19b7191-9554-47e9-af6e-61e0a8926620)

**Comment by timber-they** [comment]
This issue is also solved by setting the SITE_ID back to 2.

**Comment by jona159** [comment]
Going to close, since this is in ```Done```
