### ISSUE TITLE
Change email address at institution when ownership changes

### ISSUE THREAD

**Issue by JuliaKleeberger** [mint-o-badges/badgr-server#181]
**Change email address at institution when ownership changes**
Paste the test case here.

**Describe the bug**
I created the institution "Deutsche Telekom Stiftung". after that I added another person as owner and got deleted. Now I am no longer part of the institution but I am still the contact person for the institution, that means my email is still shown as contact detail when looking at the institution 

**To Reproduce**

**Expected behavior**
The contact email address for the institution should always be one of the owner of the institution 

In addition a function/ button where the contact address for the institution can be changed should be in the institution profile 

**Screenshots**

![image](https://github.com/mint-o-badges/badgr-ui/assets/12052169/2a0845a3-1111-4019-8e4d-b957a0865700)

**Desktop (please complete the following information; remove if not applicable):**

-   OS: [e.g. Windows 10, MacOS 14.03, Ubuntu]
-   Browser [e.g. chrome, safari]
-   Version [e.g. 22]

**Smartphone (please complete the following information; remove if not applicable):**

-   Device: [e.g. iPhone6]
-   OS: [e.g. iOS8.1]
-   Browser [e.g. stock browser, safari]
-   Version [e.g. 22]

**Additional context**
Add any other context about your observations here.

**Comment by timber-they** [comment]
We realized that it's not clear whether this ticket is about the case where the user is *deleted* or where the user is just *removed* from the issuer. So far I've implemented the case where the user is deleted, but I'm also going to implement it where the user is removed.

**Comment by zven** [comment]
@timber-they According to my understanding it's about what happens when the user is just _removed_ 

Addressing the issue of manually editing the contact email address of the issuer in a separate card is a good idea. 👍
