### ISSUE TITLE
server: redirect www.openbadges.education to openbadges.education

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-server#194]
Atm, the redirect from www.openbadges.education to openbadges.education does not work properly and gives as a security warning:

![Image](https://github.com/user-attachments/assets/7ad0a164-7bea-4613-8596-ef878e8ff25d)

**Comment by zven** [comment]
We let Chris configure the DNS properly and don't need to change anything on our side.

**Comment by zven** [comment]
Update: Does not work in Chrome so we should configure our `nginx` in a way that the redirect works.

**Comment by zven** [comment]
Another update: Chrome has not been the problem: With the DNS redirect, `https://www.openbadges.education` does not work since the certificate does not fit. If you type only `www.openbadges.education`, it worked. Long story short: We configure a redirect in our `nginx`.

**Comment by timber-they** [comment]
Note that we use `traefik` as reverse proxy for HTTPS, not `nginx`. Doesn't really matter though

**Comment by timber-they** [comment]
@zven the easiest seems to be to *also* allow www connections (because of the way we use `traefik`). Does this also meet the requirements? That's the way I implemented it now. Otherwise I'll have to set up another `traefik` container, which is also not too much work.

**Comment by timber-they** [comment]
If this is also supposed to be supported on staging / develop and / or on api.*, those DNS entries first need to be added as well.
