### ISSUE TITLE
Update deployed version if PR changed

### ISSUE THREAD

**Issue by timber-they** [mint-o-badges/badgr-server#21]
If, after a PR was created, new changes are made, the deployed package doesn't update.
This also means that we can't set the deployed version to track `main`, because it doesn't update automatically, if `main` got updated.

**Comment by timber-they** [comment]
I've created a CRON job on the staging server that makes sure the newest version from main is being used. I'm not sure this also makes sense for the deployment server, but for that we would *at least* need a dedicated branch for the deployment server. Maybe it still makes more sense to manually make sure that the newest version is deployed. I used the following script for this:
```bash
#!/bin/bash
# This script is run periodically by a CRON job to ensure the latest image of `main` is deployed
# It is heavily inspired by https://nicolaiarocci.com/how-to-automatically-pull-and-deploy-updated-docker-images/
set -e
readonly IMAGE=ghcr.io/mint-o-badges/badgr-server # Or badgr-main
readonly TAG=main

out=$(docker pull $IMAGE:$TAG)

if [[ $out != *"up to date"* ]]; then
	echo "An updated image has been downloaded for '$IMAGE:$TAG'"
	docker compose down
	docker compose up -d
else
	echo "no updates available for '$IMAGE:$TAG'"
fi
```
It is *in review*, because it needs to be verified that this works by merging stuff into `main`.

**Comment by timber-they** [comment]
Moving this back to *In Progress*, since it feels like it makes sense to switch to watchtower after all.

**Comment by timber-they** [comment]
It should now be fully functional (and using watchtower), so please report any errors :)

**Comment by jona159** [comment]
Going to close this, since it is in ```Done```
