### ISSUE TITLE
server: add license information to badge class

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-server#257]
There is an exension to do exactly that: https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/extensions/index.html#LicenseExtension

This is related to the terms of service feature: https://github.com/mint-o-badges/badgr-ui/issues/746

UI for license information is already implemented: https://github.com/mint-o-badges/badgr-ui/issues/712

Note: we will only support cc zero as highligted in https://github.com/mint-o-badges/badgr-ui/issues/712
https://creativecommons.org/publicdomain/zero/1.0/

**Comment by zven** [comment]
@jona159 I also linked you here since this is part of the whole newsletter + terms of service feature.

**Comment by zven** [comment]
@zven What happens to "old" badges?

**Comment by timber-they** [comment]
Please link the PR.

**Comment by zven** [comment]
@timber-they It looks like everything regarding the newsletter and terms of service that is UI-related is here https://github.com/mint-o-badges/badgr-ui/pull/715
and server-related is here: https://github.com/mint-o-badges/badgr-server/pull/273 
@jona159 Is my assumption correct?

**Comment by jona159** [comment]
> @timber-they It looks like everything regarding the newsletter and terms of service that is UI-related is here [mint-o-badges/badgr-ui#715](https://github.com/mint-o-badges/badgr-ui/pull/715) and server-related is here: #273 @jona159 Is my assumption correct?

Yes!

**Comment by zven** [comment]
Cleaning up the redundant issues that are related to the newsletter and terms of service feature (and there is only one PR for UI and server each). Hence closed as duplicate of https://github.com/mint-o-badges/badgr-ui/issues/746
