### ISSUE TITLE
server: export script for list of emails and names of registered users

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-server#269]
For sending out the terms of service (and newsletter) email, we need to export the list of primary emails of currently registered users (part of this feature set: https://github.com/mint-o-badges/badgr-ui/issues/746)

As already discussed with @jona159, writing an export script would make the most sense here.

**Comment by jona159** [comment]
Follow these steps to run the script: 

1. create a file ```user_emails.txt``` on the server under ```docker/badgr-server``` 
2. You might need to set permissions : ```chmod 666 user_emails.txt
3. Execute script with ```docker compose exec api python manage.py export_emails```

The emails should now be in the user_emails.txt file

**Comment by zven** [comment]
Suggestion: A `.csv`-file?

**Comment by jona159** [comment]
Adjusted the script to generate a CSV-file
