### ISSUE TITLE
validation for new extension fails

### ISSUE THREAD

**Issue by jona159** [mint-o-badges/badgr-server#32]
When trying to add a new extension to the badge creation process, the validation for the extensions fails with the error: ```extensions
: 
["Could not determine extension type to test"]``` 

The error comes from the ```openbadges-validator-core```package and is thrown [here](https://github.com/1EdTech/openbadges-validator-core/blob/6fe7402373d1059bfb3a968802032b44b37455ed/openbadges/verifier/tasks/extensions.py#L119C9-L119C80)

The ```openbadges-validator-core``` itself builds on the ```badgecheck``` package which we also use. In the ```badgecheck``` package the error can also be found [here](https://github.com/edubadges/badgecheck/blob/af17eec9535cea6857c8dcf40b9ff49d07ad1c34/openbadges/verifier/tasks/extensions.py#L119).

Noteworthy, a _TODO_ comment in the ```requirements.txt```states that the ```badgecheck``` package should be replaced with the [openbadges](https://pypi.org/project/openbadges/) package to resolve dependency conflict.

In our backend [this line](https://github.com/mint-o-badges/badgr-server/blob/main/apps/mainsite/validators.py#L67) in the validator class ```BadgeExtensionValidator``` leads to the error. The ```BadgeExtensionValidator``` is in turn used in the ```BadgeClassSerializer``` for the extension property [here](https://github.com/mint-o-badges/badgr-server/blob/main/apps/issuer/serializers_v1.py#L371). 

For now the workaround is to remove ``` validators``` property.

**Comment by timber-they** [comment]
This is solved with the following patch:
```diff
diff --git a/apps/mainsite/static/extensions/CompetencyExtension/context.json b/apps/mainsite/static/extensions/CompetencyExtension/context.json
index f35f66d7..05282e20 100644
--- a/apps/mainsite/static/extensions/CompetencyExtension/context.json
+++ b/apps/mainsite/static/extensions/CompetencyExtension/context.json
@@ -6,9 +6,9 @@
     },
     "obi:validation": [
       {
-        "obi:validatesType": "extensions:Competency",
+        "obi:validatesType": "extensions:CompetencyExtension",
         "obi:validationSchema": "http://localhost:8000/static/extensions/CompetencyExtension/schema.json"
       }
     ]
   }
-  
\ No newline at end of file
+  
```

Since there's no dedicated branch for this issue, the change will be incorporated in the current development and no review is necessary yet. Thus I'm closing this issue.
