### ISSUE TITLE
server: Environment variable handling

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-server#50]
Check out badgr-server repository in reedu organisation and check the `.env` file handling

NOTE: Unclear what that means. I can't find any file called `.env` in the `badr-server` repo. We do, however, use the `.env` file in our server for versioning, which makes the automatic deployment possible.

**Comment by zven** [comment]
@mpfeil Is this issue still important? Given that we are (successfully) running a system for some weeks I have the feeling that we might have outlived this issue.

**Comment by mpfeil** [comment]
I am not sure how the `badgr-server` configuration is handled right now. Before I left for parental leave the server was configured with [`.py`](https://github.com/mint-o-badges/badgr-server/blob/main/.docker/etc/settings_local.dev.py.example) files. These are Python specific files and not sure if all admins (who are operating and running software) know Python :smile:

But I guess they know how to handle `.env` files. So in the end it is a matter of taste. Feel free to close this issue.

**Comment by zven** [comment]
Ah, I see. @timber-they Do you have any input here?

**Comment by zven** [comment]
stale
