### ISSUE TITLE
server: Remove/Update links to social media in email

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-server#53]
Currently, there are several links to social media which seems to be outdated. You can see them in emails of awarded badge. My suggestion is to remove them unless we already have accounts in the mentioned social media.

**Comment by zven** [comment]
@YouQam You created this issue as a draft: Have you verified that those links are actually links to _our_ social media accounts? According to my understanding they simply give you the option to add that particular badge to your social own social media account (via the links provided in the mail).

**Comment by YouQam** [comment]
You are right, this is for sharing earned badge. I think we can delete this ticket.

**Comment by zven** [comment]
Nothing to be done here since this does not concern our social media profiles
