### ISSUE TITLE
server: restyle badge received email

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-server#91]
While the current badge email now contains updated information, we still need to re-style it to match the new CI.

Details and content follow.

**Comment by zven** [comment]
@Annicelia You created one design here: https://www.figma.com/file/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?type=design&node-id=2156-3338&mode=design&t=tmIqkuGgv8q7qiJf-4
Sinc it's not in "Final für Entwicklung" we should not start with that one yet, right?

**Comment by Annicelia** [comment]
@zven I had to clarify some things but just moved it to "Final für Entwicklung" :) so you can start with it now
![Bildschirmfoto 2024-05-08 um 10 29 20](https://github.com/mint-o-badges/badgr-server/assets/164371483/39a1917d-7f39-427b-958a-fc9559205965)

**Comment by zven** [comment]
Link to updated design can be found here: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=2966-5082&t=HjsuWBthPlu0fgPk-4

**Comment by zven** [comment]
@Annicelia Do you tell us once you've updated the email with the mbr-Section?

**Comment by zven** [comment]
Next to the previously linked design is now also the mobile version

**Comment by Annicelia** [comment]
@zven I adapted the MBR-section according to Uwe Rotters wishes ;) (see linked figma sections)
https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=3456-6854&t=ukT7BPUdx3A3prUc-4
https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=3519-7110&t=ukT7BPUdx3A3prUc-4

![Image](https://github.com/mint-o-badges/badgr-server/assets/164371483/f2a9980a-2429-4bf2-9e3f-5e8abdc7dd7d)
![Image](https://github.com/mint-o-badges/badgr-server/assets/164371483/62528356-a22e-4075-95b2-ab5b749da3a8)

![Image](https://github.com/mint-o-badges/badgr-server/assets/164371483/703cc024-83e1-4def-90fa-1829f04edb8c)

**Comment by zven** [comment]
@Annicelia At this point, it's a bit unclear if we can download an email attachment via an embedded link from the same email. In case that does not work, we would simply remove that sentence.

**Comment by zven** [comment]
Currently waiting for @Annicelia to clarify if a layout width of 600 px is also suitable.

**Comment by Annicelia** [comment]
I adapted the layout to 600 px with: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=3930-12044&t=kEhrP9DAKPj1Pf8j-4
mobile:https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=2966-5869&t=kEhrP9DAKPj1Pf8j-4

**Comment by zven** [comment]
@Annicelia And I added some comments to clarify / simplify the link behaviour. ;-)

**Comment by jona159** [comment]
@Annicelia would it be possible for you to export the image in the top right (```Was bringen mir Badges?```) as a PNG?

**Comment by Annicelia** [comment]
![was-bringen-badges-text](https://github.com/mint-o-badges/badgr-server/assets/164371483/6720a0a8-76ba-4ce7-930a-45dfa3e91a6c)
![wasbringenbadges](https://github.com/mint-o-badges/badgr-server/assets/164371483/97fc61af-911b-47bd-8e22-5c00e506bb67)
@jona159 sure :)

**Comment by Annicelia** [comment]
@jona159 I added three small textual changes (marked in red and with red arrow): ![Bildschirmfoto 2024-06-25 um 16 40 50](https://github.com/mint-o-badges/badgr-server/assets/164371483/784b01a7-5b8f-410e-b039-f00e00d75f2a)

**Comment by jona159** [comment]
Thanks @Annicelia ! Just a small suggestion: Since a logo is not mandatory for an issuer as of now, below ```Vergeben von``` i think we should maybe also include the issuer name ("Organisationsname"). Otherwise it would be empty there. Do you agree?

**Comment by Annicelia** [comment]
@jona159 I agree, but would it also be possible to make a logo mandatory for issuers to upload? In fact we were talking at mycelia about that recently because it would give a nicer impression on the website as well

**Comment by jona159** [comment]
@Annicelia Sure, from a technical standpoint it is possible. I will talk to @zven about it

**Comment by zven** [comment]
@Annicelia and @jona159 Another detail: Since the MBR-Login is still in its closed beta state, we should not advertise it in the email yet.

**Comment by Annicelia** [comment]
@jona159 please use the new design of the competencies (grey) in the badge received mail as well: https://www.figma.com/design/rq5IOcBWjVAl7tmvtq0GqS/Use-Cases?node-id=5081-41085&t=d9SsmlbYf6oxzwQ5-4

![Image](https://github.com/mint-o-badges/badgr-server/assets/164371483/9863262e-bc4a-4bac-8bf6-320ae566b644)
