### ISSUE TITLE
server: backups?

### ISSUE THREAD

**Issue by zven** [mint-o-badges/badgr-server#99]
Investigate: How are currently backing up our server?

**Comment by timber-they** [comment]
@zven 
- We have automatic Hetzner backups for both Staging (~8GB per backup) and Production (~5GB per backup)
- The backups are done once a day
- They are retained for 7 days (more specifically, there's 7 backup slots and the oldest one gets deleted once all are full. So if manual backups are created, this time range could become less than 7 days)
- This strategy costs us 20% of the "normal" server cost, so 1,38€ for production and 0,52€ for staging
- They *should* be easy to apply, but I didn't test it (yet)
- They are also convertable to snapshots; we are not automatically creating snapshots though

Are there any more questions or requirements?

**Comment by umut0** [comment]
Just be aware that the Hetzner backups only works for the "main" volume. If you attached extra volumes on the instance those will not be in the backup. As far as i know we do not have extra volumes at the moment.

**Comment by zven** [comment]
@timber-they Perfect overview, thanks! :-) I think that satisfies our needs for information (both regarding backups _and_ information about retention of deleted user data as part of backups)

@umut0 Good point, we should definitely keep that in mind.
